export const genresAndStyles = [
  "Abstract",
  "Acid",
  "Acid House",
  "Acid Jazz",
  "Afro-Cuban Jazz",
  "Alternative Rock",
  "Ambient",
  "Avantgarde",
  "Big Beat",
  "Bleep",
  "Breakbeat",
  "Breakcore",
  "Breaks",
  "Broken Beat",
  "Chiptune",
  "Classical",
  "Comedy",
  "Contemporary Jazz",
  "Cut-up/DJ",
  "Dark Ambient",
  "Deep House",
  "Deep Techno",
  "Dialogue",
  "Disco",
  "Downtempo",
  "Drum n Bass",
  "Dub",
  "Dub Techno",
  "Electro",
  "Electroacoustic",
  "Electronic",
  "Experimental",
  "Field Recording",
  "Funk",
  "Funk / Soul",
  "Future Jazz",
  "Garage House",
  "Ghettotech",
  "Glitch",
  "Goa Trance",
  "Hard House",
  "Hard Trance",
  "Hardcore",
  "Hip Hop",
  "House",
  "IDM",
  "Illbient",
  "Instrumental",
  "Jazz",
  "Jazz-Funk",
  "Jungle",
  "Latin",
  "Leftfield",
  "Minimal",
  "Minimal Techno",
  "Modern",
  "Neo Soul",
  "Progressive House",
  "Progressive Trance",
  "Psychedelic",
  "Psychedelic Rock",
  "Rock",
  "Salsa",
  "Soundtrack",
  "Stage & Screen",
  "Tech House",
  "Techno",
  "Trance",
  "Tribal",
  "Tribal House",
  "Trip Hop",
];
